name: $(Date:yyyy-MM-dd)-$(Rev:r)

variables:
- group: Java-Gatling
- group: celula-testing

jobs:
- job: GatlingTestJob
  steps:

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'test'
      options: '-DskipTests=true'
    displayName: 'Build Gatling project'
    
  - script: |
      mvn gatling:test -DbaseURL='https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' -Dgatling.simulationClass=microservices.simulations.CelulaTestplan -Dusers=5 -Dramp=1
    displayName: 'Run Gatling Simulation'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'target/gatling'
      artifact: 'gatling-results'
      publishLocation: 'pipeline'
    displayName: 'Prepare Gatling Reports'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'target/gatling'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: 'target/gatling/Report-$(Build.BuildNumber).zip'
      replaceExistingArchive: true


